"""add category position, menu item location, site settings

Revision ID: 1a4999d0411e
Revises: 3fdb4dbf5535
Create Date: 2026-07-12 16:48:30.830277

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4999d0411e'
down_revision: Union[str, None] = '3fdb4dbf5535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


site_settings_table = sa.table(
    "site_settings",
    sa.column("site_name", sa.String),
    sa.column("site_icon", sa.String),
    sa.column("site_icon_color", sa.String),
    sa.column("updated_at", sa.DateTime),
)

categories_table = sa.table(
    "categories",
    sa.column("id", sa.Integer),
    sa.column("name", sa.String),
    sa.column("position", sa.Integer),
)

menu_items_table = sa.table(
    "menu_items",
    sa.column("label", sa.String),
    sa.column("url", sa.String),
    sa.column("icon", sa.String),
    sa.column("position", sa.Integer),
    sa.column("is_active", sa.Boolean),
    sa.column("open_in_new_tab", sa.Boolean),
    sa.column("location", sa.String),
    sa.column("created_at", sa.DateTime),
    sa.column("updated_at", sa.DateTime),
)


def upgrade() -> None:
    bind = op.get_bind()

    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('site_icon', sa.String(length=50), nullable=False),
    sa.Column('site_icon_color', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('position', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.create_index(batch_op.f('ix_categories_position'), ['position'], unique=False)

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('location', sa.String(length=20), nullable=False, server_default='navbar')
        )
        batch_op.create_index(batch_op.f('ix_menu_items_location'), ['location'], unique=False)

    now = datetime.now(timezone.utc)

    # site_settings: tekil satır, .env'deki mevcut APP_NAME ile tohumlanır.
    try:
        from app.config import settings
        default_name = settings.app_name
    except Exception:
        default_name = "Download Sitesi"

    op.bulk_insert(
        site_settings_table,
        [{
            "site_name": default_name,
            "site_icon": "download-cloud",
            "site_icon_color": "blue",
            "updated_at": now,
        }],
    )

    # Kategori sıralaması: mevcut alfabetik görünümü koru (isim sırasına göre).
    categories = bind.execute(
        sa.select(categories_table.c.id).order_by(categories_table.c.name)
    ).fetchall()
    for position, (cat_id,) in enumerate(categories):
        bind.execute(
            categories_table.update()
            .where(categories_table.c.id == cat_id)
            .values(position=position)
        )

    # Footer'da önceden sabit metin olan "Güvenli İndirmeler" ibaresini gerçek,
    # düzenlenebilir bir footer menü öğesine dönüştür (görünüm bozulmasın diye).
    op.bulk_insert(
        menu_items_table,
        [{
            "label": "Güvenli İndirmeler",
            "url": "#",
            "icon": "shield-check",
            "position": 0,
            "is_active": True,
            "open_in_new_tab": False,
            "location": "footer",
            "created_at": now,
            "updated_at": now,
        }],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_items_location'))
        batch_op.drop_column('location')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_position'))
        batch_op.drop_column('position')

    op.drop_table('site_settings')
    # ### end Alembic commands ###
