"""add is_official_source to downloads

Revision ID: 3fdb4dbf5535
Revises: edf48226d0e3
Create Date: 2026-07-12 16:16:42.492075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fdb4dbf5535'
down_revision: Union[str, None] = 'edf48226d0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        # Mevcut kayıtlar resmî kaynak kabul edilir (server_default SQLite için zorunlu).
        batch_op.add_column(
            sa.Column('is_official_source', sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_column('is_official_source')

    # ### end Alembic commands ###
