"""add_os_icon_fields

Revision ID: aed7b59f7af4
Revises: 7960f5bd11f3
Create Date: 2026-06-01 19:13:40.732503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed7b59f7af4'
down_revision: Union[str, None] = '7960f5bd11f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_image_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('icon_image_url', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('os_compatibility', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_column('os_compatibility')
        batch_op.drop_column('icon_image_url')
        batch_op.drop_column('icon_image_path')

    # ### end Alembic commands ###
